name: Events Demo
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying
        run: echo "Deployingggg...."
